# Copyright (c) 2026 Veritas Aequitas Holdings LLC. All rights reserved.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "malwar.fullname" . }}
  labels:
    {{- include "malwar.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.malwar.apiKeys }}
  MALWAR_API_KEYS: {{ join "," .Values.malwar.apiKeys | b64enc | quote }}
  {{- end }}
  {{- if .Values.malwar.anthropicApiKey }}
  MALWAR_ANTHROPIC_API_KEY: {{ .Values.malwar.anthropicApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.malwar.webhookUrls }}
  MALWAR_WEBHOOK_URLS: {{ join "," .Values.malwar.webhookUrls | b64enc | quote }}
  {{- end }}
  {{- if .Values.malwar.webhookSecret }}
  MALWAR_WEBHOOK_SECRET: {{ .Values.malwar.webhookSecret | b64enc | quote }}
  {{- end }}
